export const CHANGE_TOP_BANNER = "recommend/CHANGE_TOP_BANNER"
export const CHANGE_HOT_RECOMEND = "recommend/CHANGE_HOT_RECOMEND"
export const CHANGE_NEW_ALBUMS = "recommend/CHANGE_NEW_ALBUMS"

export const CHANGE_SOAR_RANKING = "recommend/CHANGE_SOAR_RANKING"
export const CHANGE_NEW_SONG_RANKING = "recommend/CHANGE_NEW_SONG_RANKING"
export const CHANGE_ORIGINAL_RANKING = "recommend/CHANGE_ORIGINAL_RANKING"